### ISSUE TITLE
use AirMonitorPlots::monitor_ggDailyHourlyBarplot()

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/monitoring-custom-service#1]
**NOTE:  This work should be done on a separate branch. Jon will merge after testing.**

After creating `AirMonitorPlots::monitor_ggDailyHourlyBarplot()`, this service can now use that function instead of `PWFSLSmokePlots::createTarnayPlot()`. After this change, we can remove the *PWFSLSmokePlots* package entirely as that function was its entire. purpose.

Things should be as simple as replacing the following chunk of code in `monitor_custom/R/dailyhourlybarplot/createProduct.R`:

```
  plot <- PWFSLSmokePlots::createTarnayPlot(
    monitors = monitorIDs,
    data = ws_monitor,
    tlim = tlim,
    columns = columns,
    title = title,
    xLabel = xLabel,
    yLabel = yLabel,
    includeLink = includeLink,
    hourlyType = hourlyType,
    includeThirdCol = includeThirdCol
  )
```

This call should now be to able to use `monitor_ggDailyHourlyBarplot()`, paying attention to the following changes:

- [x] **Need to use `startdate` and `endnote` parameters rather than `tlim`**
- [x] Remove `includeThirdCol` as it was never used.
- [x] Remove all references to `includeThirdCol` in other parts of the code so that no "cruft" remains related to this.

**Comment by tabrasel** [comment]
When the app is run in RStudio, switching from `tlim` to `startdate` and `enddate` results in an error upon an API request.

Example request:
```
http://localhost:8080/monitor-custom/dev/dailyhourlybarplot?monitorids=410510080_01
```

Result:
```
{
    "status":"error",
    "status_code":500,
    "errors":"Error : Error in .balanceCrdsTimes(crdsmtx, dateTime) : \n  mismatch in number of coordinates and times\n"
}
```

This seems to be a problem with the `ws_monitor` object passed into `monitor_ggDailyHourlyBarplot()`, since if I replace:

```
plot <- monitor_ggDailyHourlyBarplot(
    ws_monitor = ws_monitor,
    ...
```

with:

```
plot <- monitor_ggDailyHourlyBarplot(
    ws_monitor = monitor_loadDaily(),
    ...
```

Then the plot generates just fine. Maybe this is a byproduct of running the app in RStudio, but I never encountered this problem when I replaced `createTarnayPlot()` with `monitor_ggDailyHourlyBarplot()` a few days ago. 

As for what's wrong with the `ws_monitor` object being passed in, it looks like it has something to do with the `dataDir` arg in the `monitor_load()` call in `createDataList.R`:

```
ws_monitor <- PWFSLSmoke::monitor_load(
        startdate = startdate,
        enddate = enddate,
        monitorIDs = monitorIDs,
        dataDir = dataDir
)
```

If I set `dataDir = NULL`, then the plot generates just fine with this `ws_monitor` object. If `dataDir = "~/Projects/monitoring-custom-service/monitor-custom/data"` like usual, then it results in the error above. I'm not sure what role `dataDir` plays in the larger scheme of things though, so I won't be making that change yet.

**Comment by jonathancallahan** [comment]
Aha! 

In order to reduce internet traffic and load times, these services are configured to use a `dataDir` which will override any default `baseUrl`. When `dataDir` is specified, data are loaded from this local directory.

There is a `Makefile` target called `desktop_download_data` which will copy the latest versions of various .RData files into the appropriate `dataDir`.

All you have to do is `make desktop_download_data` first and then re-source the app script.
